import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { useSession } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {session ? AuthorizeUserHomepage({ session }) : GuestHomepage()}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

function GuestHomepage() {
  return (
    <>
      Guest Homepage
      <Link href={"/login"}>
        <button>Sign In</button>
      </Link>
    </>
  );
}

function AuthorizeUserHomepage({ session }) {
  return (
    <>
      AuthorizeUser Homepage
      <h3>{session.user.name}</h3>
      <h3>{session.user.email}</h3>
      <Link href={"/login"}>
        <button>Sign In</button>
      </Link>
    </>
  );
}
